### ISSUE TITLE
Alert Assignment Property requires escaping characters

### ISSUE THREAD

**Issue by hmscott4** [hmscott4/AlertManagement#40]
Example:
```xml
	<exception ID="2" Name="Server Offline" Owner="EFG Windows Team" enabled="true">
	  <Alert Name="Failed to Connect to Computer" >
		<AlertProperty>MonitoringObjectDisplayName</AlertProperty>
		<AlertPropertyMatches>efg\.lcl</AlertPropertyMatches>
	  </Alert>
```

in this example, the period in efg.lcl requires escaping with "\".  Can we remove this requirement and make it more natural for the admin?

**Comment by randomnote1** [comment]
The escaping of the dot `.` is required because the script uses regular expressions (regex). Regex is faster and more powerful than comparison operators in PowerShell. However, I do agree it's not intuitive. Maybe we could implement [expression options like what SCOM does](https://docs.microsoft.com/previous-versions/system-center/developer/ee692979(v=msdn.10)?redirectedfrom=MSDN).

Operator | Description
-- | --
MatchesWildcard | The expression evaluates as true if it matches the specified wildcard expression. The following wildcard characters are allowed:<ul><li># — represents a number [0–9].</li><li>? — represents any single character.</li><li>* — represents any sequence of characters.</li><li>\ — escapes the following character; for example, \# is used to specify the # character.</li></ul>
ContainsSubstring | Expression evaluates as true if it contains the substring specified in the pattern. The pattern is mapped to a regular expression, such as "^.*EscapedPattern.*$".
MatchesRegularExpression | The expression evaluates as true if it matches the specified regular expression pattern. The regular expression evaluation uses the ATL regular expression engine.
DoesNotContainSubstring | The expression evaluates as true if it does not contain the substring specified in the pattern.
DoesNotMatchWildcard | The expression evaluates as true if it does not match the specified wildcard pattern.
DoesNotMatchRegularExpression | The expression evaluates as true if it does not match the specified regular expression pattern.

**Comment by hmscott4** [comment]
Closing this issue out for now.  Testing showed that efg.lcl worked just the same as efg\.lcl.
